'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Dictionnaire de traductions
const translations = {
  fr: {
    // Navigation
    about: 'À propos',
    pricing: 'Tarifs',
    contact: 'Contact',
    login: 'Connexion',
    register: 'Inscription',
    go_to_offers: 'Voir les offres',
    reset_password: 'Réinitialiser le mot de passe',
    dashboard: 'Tableau de bord',
    clients: 'Clients',
    prospects: 'Prospects',
    projects: 'Projets',
    project: 'Projet',
    mentors: 'Mentors',
    newsletters: 'Newsletters',
    profile: 'Profil',
    logout: 'Déconnexion',
    back: 'Retour',
    settings: 'Paramètres',
    settings_description: 'Personnalisez votre expérience',
    appearance: 'Apparence',
    appearance_desc: "Choisissez le thème de l'interface",
    theme_light: 'Clair',
    theme_dark: 'Sombre',
    theme_system: 'Système',
    theme_light_desc: 'Interface lumineuse et épurée',
    theme_dark_desc: 'Interface sombre pour réduire la fatigue oculaire',
    theme_system_desc: 'Suivre les préférences de votre appareil',
    current_theme: 'Thème actuel',
    language: 'Langue',
    language_desc: "Choisissez la langue de l'interface",
    settings_saved_locally: 'Vos préférences sont enregistrées localement dans votre navigateur.',

    // Sidebar management
    sidebar_management: 'Gestion de la sidebar',
    sidebar_management_desc: 'Sélectionnez les éléments à afficher',
    reset: 'Réinitialiser',
    reset_desc: 'Restaurer les valeurs par défaut',
    reset_sidebar: 'Afficher tous les liens',
    visible_links: 'Liens visibles',
    always_visible_links: 'Le tableau de bord, le profil et la déconnexion sont toujours visibles.',
    links_visible: 'liens affichés',
    theme: 'Thème',
    navigation: 'Navigation',

    // Notifications settings
    notifications: 'Notifications',
    email_notifications: 'Notifications email',
    email_notifications_desc: 'Choisissez les emails que vous souhaitez recevoir',
    notif_new_project: 'Nouveau projet',
    notif_new_invoice: 'Nouvelle facture créée',
    notif_invoice_paid: 'Facture payée',
    notif_collaboration: 'Invitation de collaboration',
    notif_newsletter: 'Newsletter et actualités',
    notification_frequency: 'Fréquence',
    notification_frequency_desc: 'À quelle fréquence recevoir les emails',
    instant: 'Instantané',
    daily: 'Quotidien',
    weekly: 'Hebdomadaire',
    never: 'Jamais',

    // Format settings
    format: 'Format',
    date_format: 'Format de date',
    date_format_desc: 'Comment afficher les dates',
    currency_desc: 'Devise par défaut pour les montants',
    timezone: 'Fuseau horaire',
    timezone_desc: 'Votre fuseau horaire actuel',

    // Invoice settings
    invoicing: 'Facturation',
    payment_delay: 'Délai de paiement',
    payment_delay_desc: 'Délai par défaut sur les nouvelles factures',
    default_tax_rate: 'Taux de TVA par défaut',
    default_tax_rate_desc: 'TVA appliquée automatiquement',
    invoice_prefix: 'Préfixe de numérotation',
    invoice_prefix_desc: 'Préfixe des numéros de facture',
    auto_numbering: 'Numérotation automatique',
    auto_numbering_desc: 'Générer automatiquement les numéros',
    legal_mentions: 'Mentions légales',
    legal_mentions_desc: 'Texte affiché en bas des factures',
    legal_mentions_placeholder: 'Ex: TVA non applicable, art. 293 B du CGI...',
    example: 'Exemple',
    enabled: 'Activé',
    disabled: 'Désactivé',

    // Auth
    welcome_back: 'Bon retour',
    create_account: 'Créer un compte',
    sign_in: 'Se connecter',
    sign_up: "S'inscrire",
    username: "Nom d'utilisateur",
    email: 'Email',
    password: 'Mot de passe',
    confirm_password: 'Confirmer le mot de passe',
    forgot_password: 'Mot de passe oublié ?',
    verify_email: "Vérifier l'email",

    // Profile
    edit_profile: 'Modifier le profil',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    personal_info: 'Informations personnelles',
    account_status: 'Statut du compte',
    confirmed_account: 'Compte confirmé',
    pending_account: 'Compte en attente',
    last_updated: 'Dernière mise à jour',
    member_since: 'Membre depuis',

    //Your Subscription
    your_subscription: 'Votre abonnement',
    edit_subscription: 'Modifier mon abonnement',
    trial_subscription: "Version d'essai gratuite",
    no_subscription_found: 'Aucun abonnement',
    subscription_details: "Détails de l'abonnement",
    active_subscription: 'Abonnement actif',
    quick_actions: 'Actions rapides',
    view_all_plans: 'Voir tous les plans',
    back_to_profile: 'Retour au profil',
    need_help: "Besoin d'aide ?",
    contact_support_message:
      "Contactez notre équipe de support pour obtenir de l'aide.",
    contact_support: 'Contacter le support',
    upgrade_plan: 'Mettre à niveau',
    cancel_subscription: "Annuler l'abonnement",
    //Prospects
    new_prospect: 'Nouveau prospect',
    new_prospects_this_month: 'Nouveaux prospects ce mois',
    answers: 'Réponses',
    contacted: 'Contactés',
    list_of_prospects: 'Liste des prospects',
    search_by_name_or_email: 'Rechercher par nom ou email...',
    no_prospects_found: 'Aucun prospect trouvé',
    to_be_contacted: 'À contacter',
    answer: 'Réponse',
    status: 'Statut',
    creation_date: 'Date de création',

    // Messages
    error_loading_profile: 'Erreur lors du chargement du profil',
    error_updating_user: "Erreur lors de la mise à jour de l'utilisateur",
    profile_updated_success: 'Profil mis à jour avec succès',
    error_updating: 'Erreur lors de la mise à jour',
    login_success: 'Connexion réussie',
    invalid_credentials: 'Identifiants invalides',
    register_success: 'Inscription réussie, veuillez vous connecter',
    register_failed: "Échec de l'inscription",

    //Pricing_Page
    plans_associated: 'Plans associés',
    start_free_trial: "Commencer la version d'essai gratuite",
    premium_plan: 'Plan Premium',
    pro_plan: 'Plan Pro',
    pricing_page_title:
      'Choisissez la formule qui propulse votre succès freelance',
    choose_plan: 'Choisir un abonnement',
    per_month: '/mois',
    per_year: '/an',
    save_20_percent: '(économisez 20%)',
    no_features_specified: 'Aucune fonctionnalité spécifiée',
    loading_plans: 'Chargement des plans...',
    no_plans_available: 'Aucun plan disponible',
    monthly: 'Mensuel',
    yearly: 'Annuel',
    billed_yearly: 'Facturé annuellement',
    most_popular: 'Le plus populaire',
    compare_plans: 'Comparer les plans',
    features: 'Fonctionnalités',
    storage: 'Stockage',
    based_newsletters: 'Newsletters de base',
    advanced_newsletters: 'Newsletters avancées',
    personalized_newsletters: 'Newsletters personnalisées',
    priority_support: 'Support prioritaire',
    all_time_support: 'Support 24/7',
    phone_support: 'Support téléphonique',
    email_support: 'Support email',
    personalized_integrations: 'Intégrations personnalisées',
    anticipated_features: 'Accès anticipé aux nouvelles fonctionnalités',
    data_export: 'Export des données',
    advanced_reports: 'Rapports avancés',
    auto_save: 'Sauvegarde automatique',
    max_active_projects: 'Projets actifs',
    max_active_clients: 'Clients actifs',
    max_prospects_active: 'Prospects actifs',
    max_handle_mentors: 'Mentors gérés',
    max_newsletters: 'Newsletters max. par mois',
    free: 'Gratuit',
    starter: 'Starter',
    pro: 'Pro',
    expert: 'Expert',
    your_current_plan: 'Votre plan actuel',
    trial_period: "Période d'essai",
    free_trial_description:
      "Vous avez 30 jours d'essai gratuit pour tester notre application.",
    billing_type: 'Type de facturation',
    trial: 'Essai',
    active: 'Actif',

    // Projects
    new_project: 'Nouveau projet',
    tasks_pending: 'tâches en attente',
    tasks_completed: 'tâches terminées',
    activate_free_plan: 'Activer le plan gratuit',
    free_plan_confirmation_message:
      'Voulez-vous vraiment activer le plan gratuit ?',
    trial_progress_description:
      "Vous pourrez accéder à toutes les fonctionnalités de l'application pendant 30 jours.",
    free_plan_confirmation_message_button: 'Activer le plan gratuit',
    free_plan_confirmation_message_button_cancel: 'Annuler',
    activate_plan: 'Activer le plan',
    cancel_plan: 'Annuler le plan',
    cancel_plan_confirmation_message:
      'Voulez-vous vraiment annuler votre abonnement ?',
    cancel_plan_confirmation_message_description:
      "Vous perdrez accès à toutes les fonctionnalités de l'application.",
    cancel_plan_confirmation_message_button: 'Annuler le plan',
    in_progress_projects: 'Projets en cours',
    start_date: 'Date de début',
    end_date: 'Date de fin',
    title: 'Titre',
    type: 'Type',
    technologies: 'Technologies',
    // Project types
    development: 'Développement',
    design: 'Design',
    maintenance: 'Maintenance',
    project_created_success: 'Projet créé avec succès',
    project_created_error: 'Erreur lors de la création du projet',
    
    // Images
    image_updated: 'Image mise à jour',
    image_update_error: "Erreur lors de la mise à jour de l'image",
    click_to_change_photo: 'Cliquez pour changer la photo',
    // Dashboard
    total_clients: 'Total Clients',
    new_clients_this_month: 'Nouveaux clients ce mois',
    dashboard_description:
      'Gérez vos clients, prospects et projets en temps réel avec une interface intuitive et puissante',
    ready_to_transform: 'Prêt à transformer votre gestion de projet ?',
    new_clients: 'Nouveaux clients',
    new_prospects: 'Nouveaux prospects',
    completed_projects: 'Projets terminés',
    active_clients: 'Clients actifs',
    projects_in_progress: 'Projets en cours',
    conversion_rate: 'Taux de conversion',
    total_prospects: 'Total Prospects',
    total_projects: 'Total Projets',
    total_mentors: 'Total Mentors',
    clients_list: 'Liste des clients',
    prospects_list: 'Liste des prospects',
    projects_list: 'projets',
    mentors_list: 'Liste des mentors',
    recent_activity: 'Activité récente',
    statistics: 'Statistiques',
    search_project_placeholder: 'Rechercher par nom, client ou mentor...',
    no_project_found: 'Aucun projet trouvé',

    // Table Filters - Clients
    search_placeholder_clients: 'Rechercher par nom, email ou entreprise...',
    status_options_clients: 'Tous les statuts',
    status_value_clients: 'Tous les statuts',

    // Table Filters - Prospects
    search_placeholder_prospects: 'Rechercher par nom, email ou entreprise...',
    status_options_prospects: 'Tous les statuts',
    search_value_prospects: 'Rechercher...',
    status_value_prospects: 'Tous les statuts',

    // Table Filters - Mentors
    search_placeholder_mentors: 'Rechercher par nom ou email...',
    status_options_mentors: 'Tous les statuts',
    status_value_mentors: 'Tous les statuts', 

    // Common
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    warning: 'Attention',
    info: 'Information',
    hero_subtitle_top: 'Gérez votre freelancing',
    hero_title_main: 'Maîtrisez vos projets',
    hero_subtitle_bottom: 'Sans effort',
    try_for_free: 'Essayer gratuitement',
    all_statuses: 'Tous les statuts',
    no_recent_activity: 'Aucune activité récente',
    all: 'Tous',
    // Clients
    add_client: 'Nouveau client',
    no_client_found: 'Aucun client trouvé',
    no_client: 'Aucun client',
    no_client_assigned: 'Aucun client assigné',
    name: 'Nom',
    assign_project: 'Assigner un projet',
    search_project: 'Rechercher un projet',
    // 404 Page
    page_not_found: 'Page introuvable',
    page_not_found_description:
      "Désolé, la page que vous recherchez n'existe pas ou a été déplacée. Vérifiez l'URL ou utilisez les boutons ci-dessous pour naviguer.",
    go_home: "Retour à l'accueil",
    go_back: 'Retour en arrière',
    error_code: "Code d'erreur",
    contact_support_if_problem_persists:
      'Si le problème persiste, contactez notre support.',

    // Mentors
    contact_mentor: 'Contacter un mentor',
    available: 'Disponibles',
    sessions: 'Sessions',
    list_of_mentors: 'Liste des mentors',
    list_of_mentors_available_to_implement:
      'Liste des mentors disponibles à implémenter...',
    search_mentor_placeholder: 'Rechercher par nom ou email...',
    no_mentor_found: 'Aucun mentor trouvé',
    first_name: 'Prénom',
    last_name: 'Nom',
    expertises: 'Expertises',
    created_at: 'Créé le',
    updated_at: 'Mis à jour le',

    // Profile
    account_confirmed: 'Compte confirmé',
    account_pending: 'Compte en attente',
    personal_information: 'Informations personnelles',
    add_mentor: 'Nouveau mentor',

    // Payment
    payment_details: 'Détails de paiement',
    card_number: 'Numéro de carte',
    expiry_date: "Date d'expiration",
    pay: 'Payer',
    processing: 'Traitement...',
    card_information: 'Informations de la carte',

    // Usage Progress Bar
    active_projects: 'Projets actifs',
    active_prospects: 'Prospects actifs',
    active_mentors: 'Mentors actifs',
    managed_mentors: 'Mentors gérés',
    usage_progress_bar_description: 'Vous voulez augmenter vos limites ?',
    upgrade_now: 'Mettre à niveau',

    // Free Plan Limits
    free_plan_trial: 'Plan gratuit - Essai de 30 jours',
    trial_days_remaining: 'Jours restants',
    trial_expired: 'Essai expiré',
    trial_progress: "Progression de l'essai",
    trial_expired_description: "Votre période d'essai a expiré",
    trial_expired_title: "Période d'essai expirée",
    trial_expired_message:
      "Votre période d'essai gratuit de 30 jours a expiré. Pour continuer à utiliser l'application, veuillez choisir un plan.",
    choose_plan_to_continue: 'Choisissez un plan pour continuer',

    // Quota management
    quota_reached: 'Quota atteint',
    quota_reached_message: 'Vous avez atteint votre quota. Passez à un plan supérieur pour continuer.',
    upgrade_to_unlock: 'Passez à un plan supérieur pour débloquer.',
    upgrade: 'Mettre à niveau',
    dismiss: 'Fermer',
    alerts: 'Alertes',
    select_plan: 'Sélectionner ce plan',
    go_to_pricing: 'Aller aux tarifs',
    redirecting: 'Redirection...',
    checking_subscription: 'Vérification de votre abonnement...',
    days: 'jours',
    remaining: 'restants',
    started_at: 'Commencée le',

    // Support Options
    eclipse_chatbot_support: 'Assistant Eclipse',
    eclipse_chatbot_support_description: 'Assistant IA Eclipse disponible 24/7',
    email_support_description: 'Réponse sous 24h',
    phone_support_description: 'Support direct par téléphone',
    priority_phone_support: 'Support Téléphonique Prioritaire',
    priority_phone_support_description: 'Support prioritaire 24/7',
    priority_email_support: 'Support Email Prioritaire',
    priority_email_support_description: 'Réponse prioritaire sous 4h',

    // Upgrade Dropdown
    choose_upgrade_plan: 'Choisir un plan de mise à niveau',
    current_plan: 'Plan actuel',
    upgrade_to: 'Mettre à niveau vers',
    no_upgrade_available: 'Aucune mise à niveau disponible',

    // Newsletters
    add_newsletter: 'Nouvelle newsletter',
    total_newsletters: 'Total des newsletters',
    no_newsletter_found: 'Aucune newsletter trouvée',
    sent: 'Envoyées',
    open_rate: "Taux d'ouverture",
    newsletters_list: 'Liste des newsletters',
    newsletters_list_description:
      'Liste des newsletters envoyées à implémenter...',

    // Clients
    invoices: 'Factures',
    no_invoice_found: 'Aucune facture trouvée.',
    number: 'Téléphone',
    amount: 'Montant',
    revenue: "Chiffre d'affaires",
    enterprise: 'Entreprise',
    address: 'Adresse',
    website: 'Site web',
    process_status: 'Statut du processus',
    is_active: 'Actif',
    edit: 'Modifier',
    your_enterprise: 'Votre entreprise',
    edit_enterprise: 'Modifier votre entreprise',
    // Revenue
    top_project: 'Projet le plus rentable',
    top_client: 'Client le plus rentable',
    average_invoice: 'Moyenne des factures',
    due_date: "Date d'échéance",
    view_invoice: 'Voir la facture',
    add_invoice: 'Créer une facture',
    // Factures
    select_project: 'Sélectionner un projet',
    search_placeholder_factures:
      'Rechercher par référence, client ou projet...',
    no_invoices_for_project: 'Aucune facture associée à ce projet',
    create_first_invoice: 'Créer une facture',
    select_client: 'Sélectionner un client',
    total_invoices: 'Nombre de factures',
    active_factures: 'Factures payées',
    new_factures_this_month: 'Nouvelles factures ce mois',
    download: 'Télécharger',
    download_pdf: 'Télécharger PDF',
    invoice_pdf: 'Facture PDF',
    target_revenue: "Chiffre d'affaires cible",
    progress_to_target: "Progression vers le chiffre d'affaires cible",
    revenue_evolution: 'Évolution du CA',
    revenue_by_client: 'CA par client',
    invoices_by_month: 'Factures par mois',
    no_data: 'Aucune donnée',
    no_project: 'Sans projet',
    reference: 'Référence',
    currency: 'Devise',
    description: 'Description',
    note: 'Note',
    date: 'Date',
    date_due: "Date d'échéance",
    facture_status: 'Statut de la facture',
    paid: 'Payé',
    pending: 'En attente',
    draft: 'Brouillon',
    send_email: 'Envoyer un email',
    print: 'Imprimer',
    delete: 'Supprimer',
    invoice_details: 'Détails de la facture',
    services: 'Prestations',
    calculations: 'Calculs',
    subtotal: 'Sous-total',
    total_ttc: 'Total TTC',
    notes: 'Notes',
    client: 'Client',
    unit_price: 'Prix unitaire',
    total: 'Total',
    add_line: 'Ajouter une ligne',
    quantity: 'Quantité',
    unit_type: 'Type',
    billing_hour: 'Heure',
    billing_day: 'Jour',
    billing_fixed: 'Forfait',
    billing_unit: 'Unité',
    emission_date: "Date d'émission",
    overdue: 'En retard',

    // Enterprise

    create_your_enterprise: 'Créer votre entreprise',
    enterprise_name: "Nom de l'entreprise",
    enterprise_email: "Email de l'entreprise",
    enterprise_description: "Description de l'entreprise",
    siret: 'Numéro SIRET',
    siren: 'Numéro SIREN',
    vat: 'Numéro de TVA',
    vat_applicable: 'TVA applicable',
    phone_number: 'Téléphone',
    activity_domain: "Domaine d'activité",
    select_activity_domain: 'Sélectionner un domaine',
    no_enterprise_profile: "Vous n'avez pas encore de profil d'entreprise.",
    create: 'Créer',
    create_facture: 'Créer une facture',
    add: 'Ajouter',

    // Traductions manquantes ajoutées
    project_assigned_success: 'Projet assigné avec succès',
    error_not_authenticated: 'Vous devez être connecté',
    client_added_success: 'Client ajouté avec succès',
    client_deleted_success: 'Client supprimé avec succès',
    project_deleted_success: 'Projet supprimé avec succès',
    facture_deleted_success: 'Facture supprimée avec succès',
    prospect_deleted_success: 'Prospect supprimé avec succès',
    mentor_deleted_success: 'Mentor supprimé avec succès',
    delete_client: 'Supprimer le client',
    delete_project: 'Supprimer le projet',
    delete_facture: 'Supprimer la facture',
    delete_prospect: 'Supprimer le prospect',
    delete_mentor: 'Supprimer le mentor',
    choose_project: 'Choisir un projet',
    projects_available: 'projet(s) disponible(s)',
    no_unassigned_projects: 'Aucun projet disponible',
    create_project_first: "Créez d'abord un projet",
    create_new_project: 'Créer un nouveau projet',
    go_to_projects_page: 'Aller à la page projets',
    subscription_cancelled: 'Abonnement annulé',
    no_description: 'Aucune description',
    last_update: 'Dernière mise à jour',
    activating: 'Activation en cours...',
    view: 'Voir',
    factures: 'Factures',
    project_name: 'Nom du projet',
    in_progress: 'En cours',
    completed: 'Terminé',
    add_project: 'Ajouter un projet',
    add_prospect: 'Ajouter un prospect',
    actions: 'Actions',
    chatbot_support: 'Support chatbot',
    chatbot_support_description: 'Assistant IA disponible 24/7',
    subject: 'Sujet',
    no_newsletters_found: 'Aucune newsletter trouvée',
    phone: 'Téléphone',
    planning: 'Planification',
    archived: 'Archivé',
    dates: 'Dates',
    project_updated_success: 'Projet mis à jour avec succès',

    // Partage de projet & Collaboration
    share_project: 'Partager le projet',
    share: 'Partager',
    invite: 'Inviter',
    members: 'Membres',
    invite_by_email: 'Inviter par email',
    permission: 'Permission',
    view_only: 'Lecture seule',
    can_edit: 'Peut modifier',
    or: 'ou',
    copy_share_link: 'Copier le lien de partage',
    pending_invitations: 'Invitations en attente',
    no_collaborators: 'Aucun collaborateur pour le moment',
    collaborators: 'Collaborateurs',
    manage_collaborators: 'Gérer les collaborateurs',
    owner: 'Propriétaire',
    your_role: 'Votre rôle',
    collaborator: 'Collaborateur',
    share_note: 'Les collaborateurs invités ne peuvent pas supprimer ce projet.',
    invitation_sent_success: 'Invitation envoyée avec succès',
    invitation_error: "Erreur lors de l'envoi de l'invitation",
    link_copied: 'Lien copié dans le presse-papiers',
    copy_error: 'Erreur lors de la copie',
    invitation_cancelled: 'Invitation annulée',
    collaborator_removed: 'Collaborateur retiré',
    error_generic: 'Une erreur est survenue',

    // Revenue
    global_revenue_stats: 'Vue globale',  

    // Notifications
    mark_all_read: 'Tout marquer comme lu',
    no_notifications: 'Aucune notification',
    accept: 'Accepter',
    reject: 'Refuser',
    all_marked_read: 'Toutes les notifications ont été marquées comme lues',
    notification_deleted: 'Notification supprimée',
    invitation_accepted: 'Invitation acceptée ! Le projet a été ajouté à votre liste.',
    invitation_rejected: 'Invitation refusée',
    view_all_notifications: 'Voir toutes les notifications',
    just_now: "À l'instant",
    
    // Invitation de projet
    project_invitation: 'Invitation à collaborer',
    invites_you_to_collaborate: 'vous invite à collaborer sur le projet',
    collaborator_note: 'En tant que collaborateur, vous ne pourrez pas supprimer ce projet.',
    back_to_projects: 'Retour aux projets',
    expires_on: 'Expire le',
    invitation_not_found: 'Invitation non trouvée ou expirée',
    invitation_already_accepted: 'Cette invitation a déjà été acceptée',
    invitation_already_rejected: 'Cette invitation a été refusée',
    invitation_expired: 'Cette invitation a expiré',

    // Tâches de projet
    project_tasks: 'Tâches du projet',
    progress: 'progression',
    overall_progress: 'Progression globale',
    add_task: 'Nouvelle tâche',
    new_task: 'Nouvelle tâche',
    task_title: 'Titre de la tâche',
    task_description: 'Description (optionnel)',
    task_created: 'Tâche créée avec succès',
    task_updated: 'Tâche mise à jour',
    task_deleted: 'Tâche supprimée',
    confirm_delete_task: 'Supprimer cette tâche ?',
    edit_task: 'Modifier la tâche',
    no_tasks: 'Aucune tâche pour ce projet',
    no_tasks_filter: 'Aucune tâche avec ce statut',
    add_first_task: 'Ajouter une tâche',
    priority: 'Priorité',
    priority_low: 'Basse',
    priority_medium: 'Moyenne',
    priority_high: 'Haute',
    priority_urgent: 'Urgente',
    task_status_todo: 'À faire',
    task_status_in_progress: 'En cours',
    task_status_completed: 'Terminé',
    task_status_cancelled: 'Annulé',
    estimated_hours: 'Heures estimées',
    actual_hours: 'Heures réelles',
    no_collaborators_yet: 'Aucun collaborateur pour le moment',
    due_dates: 'Dates d\'échéance',
    billed: 'Facturé',

    // ProjectTasks - Vues
    cards: 'Cartes',
    table: 'Tableau',
    gantt: 'Gantt',

    // ProjectTasks - Statuts
    todo: 'À faire',
    cancelled: 'Annulé',

    // ProjectTasks - Priorités
    low: 'Basse',
    medium: 'Moyenne',
    high: 'Haute',
    urgent: 'Urgente',

    // ProjectTasks - Divers
    manage: 'Gérer',
    late: 'En retard',
    week_short: 'Sem.',
    task: 'Tâche',
    export_pdf: 'Export PDF',
    exporting: 'Export...',
    exported_on: 'Exporté le',
    export_mode: 'Mode d\'export',
    choose_export_theme: 'Choisissez le thème du PDF :',
    light: 'Clair',
    dark: 'Sombre',
    export: 'Exporter',
    file_name: 'Nom du fichier',

    // Notifications page
    notifications_description: 'Gérez vos notifications et invitations',
    no_notifications_desc: "Vous n'avez aucune notification pour le moment.",
    today: "Aujourd'hui",
    yesterday: 'Hier',
    this_week: 'Cette semaine',
    older: 'Plus ancien',
    unread: 'Non lues',
    read: 'Lues',
    filters: 'Filtres',
    notification_type: 'Type de notification',
    all_types: 'Tous les types',
    updates: 'Mises à jour',
    system: 'Système',
    invitation: 'Invitation',
    update: 'Mise à jour',
    selected: 'sélectionnée(s)',
    mark_read: 'Marquer lu',
    selected_marked_read: 'Notifications sélectionnées marquées comme lues',
    selected_deleted: 'Notifications supprimées',
    mark_as_read: 'Marquer comme lu',
    refresh: 'Actualiser',

    // Newsletter Compose
    create_newsletter: 'Créer une newsletter',
    select_template: 'Sélectionnez un template',
    choose_template: 'Choisissez un template',
    choose_template_desc: 'Sélectionnez le style qui correspond le mieux à votre message',
    template_standard: 'Standard',
    template_standard_desc: 'Newsletter classique pour vos mises à jour régulières',
    template_promotional: 'Promotionnel',
    template_promotional_desc: 'Idéal pour annoncer des offres et promotions',
    template_announcement: 'Annonce',
    template_announcement_desc: 'Pour les grandes nouvelles et annonces importantes',
    template_custom: 'Personnalisé',
    template_custom_desc: 'Créez votre propre design depuis zéro',
    feature_clean_design: 'Design épuré',
    feature_content_focus: 'Focus sur le contenu',
    feature_ideal_updates: 'Idéal pour les mises à jour',
    feature_promo_badge: 'Badge promo',
    feature_prominent_cta: 'CTA prominent',
    feature_ideal_offers: 'Idéal pour les offres',
    feature_visual_impact: 'Impact visuel fort',
    feature_centered_message: 'Message centré',
    feature_ideal_events: 'Idéal pour les événements',
    feature_total_freedom: 'Liberté totale',
    feature_no_constraints: 'Sans contrainte',
    feature_unique_design: 'Design unique',
    preview: 'Aperçu',
    send: 'Envoyer',
    previous: 'Précédent',
    next: 'Suivant',
    step_template: 'Template',
    step_content: 'Contenu',
    step_recipients: 'Destinataires',
    step_send: 'Envoi',
    write_content: 'Rédigez votre contenu',
    write_content_desc: 'Personnalisez le contenu de votre newsletter',
    footer: 'Footer',
    customize_footer: 'Personnaliser le footer',
    first_name_label: 'Prénom',
    last_name_label: 'Nom',
    email_label: 'Email',
    phone_label: 'Téléphone',
    website_label: 'Site web',
    linkedin_label: 'LinkedIn',
    twitter_label: 'Twitter / X',
    instagram_label: 'Instagram',
    facebook_label: 'Facebook',
    custom_text_label: 'Texte personnalisé (optionnel)',
    custom_text_placeholder: 'Message additionnel dans le footer...',
    unsubscribe_text_label: 'Texte de désabonnement',
    email_title_label: "Titre de l'email",
    email_title_placeholder: 'Ex: Bienvenue dans notre newsletter',
    email_subject_label: "Objet de l'email",
    email_subject_hint: 'visible dans la boîte de réception',
    email_subject_placeholder: 'Ex: Découvrez nos nouvelles fonctionnalités',
    message_label: 'Message',
    add_image: 'Ajouter une image',
    cta_section_title: "Bouton d'action (optionnel)",
    cta_text_label: 'Texte du bouton',
    cta_text_placeholder: 'Ex: En savoir plus',
    cta_link_label: 'Lien',
    banner_section_title: 'Bannière de fin (optionnel)',
    add_banner: 'Ajouter une bannière',
    banner_hint: "PNG, JPG jusqu'à 5 Mo",
    select_recipients: 'Sélectionnez les destinataires',
    select_recipients_desc: 'Choisissez qui recevra votre newsletter',
    select_all_clients: 'Sélectionner tous les clients',
    recipients_selected: 'sélectionné(s)',
    review_and_send: 'Vérifiez et envoyez',
    review_and_send_desc: "Dernière vérification avant l'envoi",
    ready_to_send: 'Prêt à envoyer ?',
    newsletter_will_be_sent: 'Votre newsletter sera envoyée à',
    recipients_count: 'destinataire(s)',
    send_now: 'Envoyer maintenant',
    sending: 'Envoi...',
    contacts: 'contact(s)',
    others: 'autres',
    mailbox_preview: 'Aperçu Boîte Mail',
    inbox: 'Boîte de réception',
    favorites: 'Favoris',
    sent_folder: 'Envoyés',
    archives: 'Archives',
    trash: 'Corbeille',
    search_placeholder: 'Rechercher...',
    now: 'Maintenant',
    to_me: 'à moi',
    select_template_preview: "Sélectionnez un template pour voir l'aperçu",
    write_message_placeholder: 'Rédigez votre message ici...',
    your_title_here: 'Votre titre ici',
    content_preview_placeholder: 'Votre contenu apparaîtra ici...',
    special_offer: 'OFFRE SPÉCIALE',
    unsubscribe: 'Se désabonner',
    please_select_recipient: 'Veuillez sélectionner au moins un destinataire',
    please_enter_subject: 'Veuillez saisir un objet',
    newsletter_sent_success: 'Newsletter envoyée à',
    newsletter_send_error: "Erreur lors de l'envoi",
    newsletter_not_found: 'Newsletter non trouvée',
    newsletter_detail: 'Détail Newsletter',
    loading_newsletter: 'Chargement de la newsletter...',
    back_to_newsletters: 'Retour aux newsletters',
    sent_at: "Date d'envoi",
    email_content: "Contenu de l'email",
    no_content: 'Aucun contenu',
    subscribers: 'Destinataires',
    no_subscribers: 'Aucun destinataire',
    quick_stats: 'Statistiques rapides',
    total_recipients: 'Total destinataires',
    email_preview: 'Aperçu de l\'email',
    email_preview_description: 'Voir l\'email dans votre boîte de réception',
    please_select_image: 'Veuillez sélectionner une image',
    image_max_size: "L'image ne doit pas dépasser 5 Mo",
    toolbar_heading1: 'Titre 1',
    toolbar_heading2: 'Titre 2',
    toolbar_paragraph: 'Paragraphe',
    toolbar_bold: 'Gras',
    toolbar_italic: 'Italique',
    toolbar_bullet_list: 'Liste à puces',
    toolbar_numbered_list: 'Liste numérotée',
    toolbar_align_left: 'Aligner à gauche',
    toolbar_align_center: 'Centrer',
    toolbar_align_right: 'Aligner à droite',
    toolbar_text_color: 'Couleur du texte',
    toolbar_insert_link: 'Insérer un lien',
    author: 'Auteur',

    internal_notes: 'Notes internes',
    private_notes: 'Notes privées',
    automatic_status: 'Statut automatique',
    blue: 'Bleu',
    emerald: 'Émeraude',
    amber: 'Ambre',
    purple: 'Violet',
    rose: 'Rose',
    cyan: 'Cyan',

    overview: 'Aperçu',
    tasks: 'Tâches',
  },

  en: {
    // Navigation
    dashboard: 'Dashboard',
    about: 'About',
    pricing: 'Pricing',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    go_to_offers: 'Go to offers',
    forgot_password: 'Forgot Password?',
    reset_password: 'Reset Password',
    verify_email: 'Verify Email',
    clients: 'Clients',
    prospects: 'Prospects',
    projects: 'Projects',
    project: 'Project',
    mentors: 'Mentors',
    newsletters: 'Newsletters',
    profile: 'Profile',
    logout: 'Logout',
    back: 'Back',
    settings: 'Settings',
    settings_description: 'Customize your experience',
    appearance: 'Appearance',
    appearance_desc: 'Choose the interface theme',
    theme_light: 'Light',
    theme_dark: 'Dark',
    theme_system: 'System',
    theme_light_desc: 'Bright and clean interface',
    theme_dark_desc: 'Dark interface to reduce eye strain',
    theme_system_desc: 'Follow your device preferences',
    current_theme: 'Current theme',
    language: 'Language',
    language_desc: 'Choose the interface language',
    settings_saved_locally: 'Your preferences are saved locally in your browser.',

    internal_notes: 'Internal Notes',
    private_notes: 'Private Notes',

    // Sidebar management
    sidebar_management: 'Sidebar Management',
    sidebar_management_desc: 'Choose which links to display in the sidebar',
    reset: 'Reset',
    always_visible_links: 'Dashboard, profile and logout are always visible.',
    links_visible: 'links visible',

    welcome_back: 'Welcome Back',
    create_account: 'Create Account',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    // Profile
    edit_profile: 'Edit Profile',
    save: 'Save',
    cancel: 'Cancel',
    personal_info: 'Personal Information',
    account_status: 'Account Status',
    confirmed_account: 'Confirmed Account',
    pending_account: 'Pending Account',
    last_updated: 'Last Updated',
    member_since: 'Member since',

    // Messages
    error_loading_profile: 'Error loading profile',
    error_updating_user: 'Error updating user',
    profile_updated_success: 'Profile updated successfully',
    error_updating: 'Error updating',
    login_success: 'Login successful',
    invalid_credentials: 'Invalid credentials',
    register_success: 'Register successful, please login',
    register_failed: 'Register failed',

    //Pricing_Page
    plans_associated: 'Plans associated',
    features_details: 'Features Details',
    features_details_description: 'Features Details Description',
    start_free_trial: 'Start Free Trial',
    premium_plan: 'Premium Plan',
    pro_plan: 'Pro Plan',
    pricing_page_title: 'Choose the Plan that Powers Your Freelance Success',
    choose_plan: 'Choose a plan',
    per_month: '/month',
    per_year: '/year',
    save_20_percent: '(save 20%)',
    no_features_specified: 'No features specified',
    loading_plans: 'Loading plans...',
    no_plans_available: 'No plans available',
    monthly: 'Monthly',
    yearly: 'Yearly',
    billed_yearly: 'Billed yearly',
    most_popular: 'Most Popular',
    compare_plans: 'Compare Plans',
    features: 'Features',
    storage: 'Storage',
    based_newsletters: 'Based Newsletters',
    advanced_newsletters: 'Advanced Newsletters',
    personalized_newsletters: 'Personalized Newsletters',
    priority_support: 'Priority Support',
    all_time_support: 'All Time Support',
    phone_support: 'Phone Support',
    email_support: 'Email Support',
    personalized_integrations: 'Personalized Integrations',
    anticipated_features: 'Anticipated Features',
    data_export: 'Data Export',
    advanced_reports: 'Advanced Reports',
    auto_save: 'Auto Save',
    max_active_projects: 'Max Active Projects',
    max_active_clients: 'Max Active Clients',
    max_prospects_active: 'Max Prospects Active',
    max_handle_mentors: 'Max Handle Mentors',
    max_newsletters: 'Max Newsletters per month',
    free: 'Free',
    starter: 'Starter',
    pro: 'Pro',
    expert: 'Expert',
    your_current_plan: 'Your Current Plan',
    trial_period: 'Trial Period',
    free_trial_description: 'You have a 30-day free trial to test our app.',
    billing_type: 'Billing Type',
    trial: 'Trial',
    active: 'Active',
    create: 'Create',
    in_progress_projects: 'Projects in Progress',

    // Settings
    theme: 'Theme',
    navigation: 'Navigation',

    // Notifications settings
    notifications: 'Notifications',
    email_notifications: 'Email notifications',
    email_notifications_desc: 'Choose which emails you want to receive',
    notif_new_project: 'New project',
    notif_new_invoice: 'New invoice created',
    notif_invoice_paid: 'Invoice paid',
    notif_collaboration: 'Collaboration invitation',
    notif_newsletter: 'Newsletter and updates',
    notification_frequency: 'Frequency',
    notification_frequency_desc: 'How often to receive emails',
    instant: 'Instant',
    daily: 'Daily',
    weekly: 'Weekly',
    never: 'Never',

    // Format settings
    format: 'Format',
    date_format: 'Date format',
    date_format_desc: 'How to display dates',
    currency_desc: 'Default currency for amounts',
    timezone: 'Timezone',
    timezone_desc: 'Your current timezone',

    // Invoice settings
    invoicing: 'Invoicing',
    payment_delay: 'Payment delay',
    payment_delay_desc: 'Default delay on new invoices',
    default_tax_rate: 'Default tax rate',
    default_tax_rate_desc: 'Tax automatically applied',
    invoice_prefix: 'Invoice prefix',
    invoice_prefix_desc: 'Prefix for invoice numbers',
    auto_numbering: 'Auto numbering',
    auto_numbering_desc: 'Automatically generate numbers',
    legal_mentions: 'Legal mentions',
    legal_mentions_desc: 'Text displayed at the bottom of invoices',
    legal_mentions_placeholder: 'Ex: VAT not applicable, article 293 B of CGI...',
    example: 'Example',
    enabled: 'Enabled',
    disabled: 'Disabled',

    // Dashboard
    total_clients: 'Total Clients',
    new_clients_this_month: 'New clients this month',
    new_prospects_this_month: 'New Prospects This Month',
    completed_projects: 'Completed Projects',
    total_prospects: 'Total Prospects',
    total_projects: 'Total Projects',
    total_mentors: 'Total Mentors',
    clients_list: 'Clients List',
    prospects_list: 'Prospects List',
    projects_list: 'projects',
    mentors_list: 'Mentors List',
    recent_activity: 'Recent Activity',
    statistics: 'Statistics',
    conversion_rate: 'Conversion Rate',
    projects_in_progress: 'Projects in Progress',
    no_recent_activity: 'No Recent Activity',
    new_project: 'New Project',
    start_date: 'Start Date',
    end_date: 'End Date',
    title: 'Title',
    type: 'Type',
    technologies: 'Technologies',
    // Project types
    development: 'Development',
    design: 'Design',
    maintenance: 'Maintenance',
    in_progress: 'In Progress',
    completed: 'Completed',
    search_project_placeholder: 'Search by name, client or mentor...',
    no_project_found: 'No project found',
    project_created_success: 'Project created successfully',
    project_created_error: 'Error creating project',
    
    // Images
    image_updated: 'Image updated',
    image_update_error: 'Error updating image',
    click_to_change_photo: 'Click to change photo',
    
    // Mentors
    contact_mentor: 'Contact a mentor',
    available: 'Available',
    sessions: 'Sessions',
    list_of_mentors: 'List of Mentors',
    list_of_mentors_available_to_implement:
      'List of Mentors Available to Implement',
    search_mentor_placeholder: 'Search by name or email...',
    no_mentor_found: 'No mentor found',
    first_name: 'First Name',
    last_name: 'Last Name',
    expertises: 'Expertises',
    created_at: 'Created At',
    updated_at: 'Updated At',
    actions: 'Actions',

    // Profile
    account_confirmed: 'Account Confirmed',
    account_pending: 'Account Pending',
    personal_information: 'Personal Information',
    add_mentor: 'Add Mentor',

    // Newsletters
    add_newsletter: 'Add Newsletter',
    total_newsletters: 'Total Newsletters',
    search_placeholder_newsletters: 'Search by title or status...',
    no_newsletter_found: 'No newsletter found',
    sent: 'Sent',
    open_rate: 'Open Rate',
    newsletter_list: 'Newsletter List',
    newsletter_list_description: 'Newsletter List Description',

    // Table Filters - Newsletters
    status_options_newsletters: 'Tous les statuts',
    status_value_newsletters: 'Tous les statuts',

    // Payment
    payment_details: 'Payment Details',
    card_number: 'Card Number',
    expiry_date: 'Expiry Date',
    pay: 'Pay',
    processing: 'Processing...',
    card_information: 'Card Information',
    // Prospects
    new_prospect: 'New Prospect',
    answers: 'Answers',
    contacted: 'Contacted',
    list_of_prospects: 'List of Prospects',
    search_by_name_or_email: 'Search by name or email...',
    no_prospects_found: 'No prospects found',
    to_be_contacted: 'To be contacted',
    answer: 'Answer',
    status: 'Status',
    creation_date: 'Creation Date',

    //Your Subscription
    your_subscription: 'Your subscription',
    edit_subscription: 'Edit subscription',
    trial_subscription: 'Free trial',
    no_subscription_found: 'No subscription found',
    subscription_details: 'Subscription Details',
    active_subscription: 'Active Subscription',
    quick_actions: 'Quick Actions',
    view_all_plans: 'View All Plans',
    back_to_profile: 'Back to Profile',
    need_help: 'Need Help?',
    contact_support_message: 'Contact our support team for assistance.',
    contact_support: 'Contact Support',
    upgrade_plan: 'Upgrade Plan',
    cancel_subscription: 'Cancel Subscription',
  
    // Usage Progress Bar
    active_projects: 'Active Projects',
    active_clients: 'Active Clients',
    active_prospects: 'Active Prospects',
    active_mentors: 'Active Mentors',
    managed_mentors: 'Managed Mentors',
    usage_progress_bar_description: 'You want to increase your limits?',
    upgrade_now: 'Upgrade now',

    // Free Plan Limits
    free_plan_trial: 'Free Plan - 30 Day Trial',
    trial_days_remaining: 'Days remaining',
    trial_expired: 'Trial expired',
    trial_progress: 'Trial progress',
    trial_progress_description: 'Your trial period is progressing',
    trial_expired_description: 'Your trial period has expired',
    trial_expired_title: 'Trial Period Expired',
    trial_expired_message:
      'Your 30-day free trial has expired. To continue using the application, please choose a plan.',
    choose_plan_to_continue: 'Choose a plan to continue',

    // Quota management
    quota_reached: 'Quota reached',
    quota_reached_message: 'You have reached your quota. Upgrade to a higher plan to continue.',
    upgrade_to_unlock: 'Upgrade to a higher plan to unlock.',
    upgrade: 'Upgrade',
    dismiss: 'Dismiss',
    alerts: 'Alerts',
    select_plan: 'Select this plan',
    go_to_pricing: 'Go to pricing',
    redirecting: 'Redirecting...',
    checking_subscription: 'Checking your subscription...',
    remaining: 'remaining',
    started_at: 'Started at',
    // Support Options
    chatbot_support: 'Chatbot Support',
    chatbot_support_description: 'AI assistant available 24/7',
    phone_support_description: 'Direct phone support',
    priority_phone_support: 'Priority Phone Support',
    priority_phone_support_description: 'Priority support 24/7',
    priority_email_support: 'Priority Email Support',
    priority_email_support_description: 'Priority response within 4h',

    // Upgrade Dropdown
    choose_upgrade_plan: 'Choose upgrade plan',
    current_plan: 'Current plan',
    upgrade_to: 'Upgrade to',
    no_upgrade_available: 'No upgrade available',
    // Common
    add: 'Add',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    hero_subtitle_top: 'Manage your freelancing',
    hero_title_main: 'Master your projects',
    hero_subtitle_bottom: 'With ease',
    try_for_free: 'Try for free',
    all_statuses: 'All statuses',
    all: 'All',
    // Clients
    add_client: 'Add Client',
    search_placeholder_clients: 'Search by name, email or company...',
    status_options_clients: 'All statuses',
    status_value_clients: 'All statuses',
    no_client_found: 'No client found',
    no_client: 'No client',
    no_client_assigned: 'No client assigned',
    name: 'Name',
    assign_project: 'Assign Project',
    search_project: 'Search Project',
    // 404 Page
    page_not_found: 'Page Not Found',
    page_not_found_description:
      'Sorry, the page you are looking for does not exist or has been moved. Check the URL or use the buttons below to navigate.',
    go_home: 'Go Home',
    go_back: 'Go Back',
    error_code: 'Error Code',
    contact_support_if_problem_persists:
      'If the problem persists, contact our support.',

    // Eclipse Chatbot
    eclipse_chatbot_support: 'Eclipse Chatbot Support',
    eclipse_chatbot_support_description: 'AI assistant available 24/7',

    // Clients
    invoices: 'Invoices',
    no_invoice_found: 'No invoice found.',
    number: 'Phone',
    amount: 'Amount',
    revenue: 'Revenue',
    enterprise: 'Enterprise',
    address: 'Address',
    website: 'Website',
    process_status: 'Process Status',
    is_active: 'Active',
    edit: 'Edit',
    your_enterprise: 'Your Enterprise',
    edit_enterprise: 'Edit your enterprise',
    // Factures
    select_project: 'Select Project',
    search_placeholder_factures: 'Search by reference, client or project...',
    select_client: 'Select Client',
    total_invoices: 'Number of invoices',
    active_factures: 'Paid invoices',
    new_factures_this_month: 'New invoices this month',
    download: 'Download',
    download_pdf: 'Download PDF',
    invoice_pdf: 'Invoice PDF',
    add_invoice: 'Add Invoice',
    add_line: 'Add Line',
    quantity: 'Quantity',
    unit_type: 'Type',
    billing_hour: 'Hour',
    billing_day: 'Day',
    billing_fixed: 'Fixed',
    billing_unit: 'Unit',
    vat_applicable: 'VAT applicable',
    overdue: 'Overdue',
    create_facture: 'Create Facture',
    // Revenue
    top_project: 'Top Project',
    top_client: 'Top Client',
    average_invoice: 'Average Invoice',
    due_date: 'Due Date',
    view_invoice: 'View Invoice',
    target_revenue: 'Target Revenue',
    progress_to_target: 'Progress to target revenue',
    revenue_evolution: 'Revenue Evolution',
    revenue_by_client: 'Revenue by Client',
    invoices_by_month: 'Invoices per Month',
    no_data: 'No data',
    global_revenue_stats: 'Global view',
    no_project: 'No project',
    reference: 'Reference',
    currency: 'Currency',
    description: 'Description',
    note: 'Note',
    date: 'Date',
    date_due: 'Due Date',
    draft: 'Draft',
    send_email: 'Send Email',
    print: 'Print',
    delete: 'Delete',
    invoice_details: 'Invoice Details',
    calculations: 'Calculations',
    subtotal: 'Subtotal',
    vat: 'VAT',
    total_ttc: 'Total TTC',
    notes: 'Notes',
    client: 'Client',
    unit_price: 'Unit Price',
    total: 'Total',
    emission_date: 'Emission Date',
    paid: 'Paid',
    pending: 'Pending',
    phone: 'Phone',
    siret: 'SIRET',
    siren: 'SIREN',
    services: 'Services',
    // Enterprise
    create_your_enterprise: 'Create your enterprise',
    enterprise_name: 'Enterprise Name',
    enterprise_email: 'Enterprise Email',
    enterprise_description: 'Enterprise Description',
    phone_number: 'Phone Number',
    activity_domain: 'Activity Domain',
    select_activity_domain: 'Select Activity Domain',
    no_enterprise_profile: "You don't have an enterprise profile yet.",

    // Missing translations added
    project_assigned_success: 'Project assigned successfully',
    error_not_authenticated: 'You must be logged in',
    client_added_success: 'Client added successfully',
    client_deleted_success: 'Client deleted successfully',
    project_deleted_success: 'Project deleted successfully',
    facture_deleted_success: 'Invoice deleted successfully',
    prospect_deleted_success: 'Prospect deleted successfully',
    mentor_deleted_success: 'Mentor deleted successfully',
    delete_client: 'Delete client',
    delete_project: 'Delete project',
    delete_facture: 'Delete invoice',
    delete_prospect: 'Delete prospect',
    delete_mentor: 'Delete mentor',
    choose_project: 'Choose a project',
    projects_available: 'project(s) available',
    no_unassigned_projects: 'No project available',
    create_project_first: 'Create a project first',
    create_new_project: 'Create a new project',
    go_to_projects_page: 'Go to projects page',
    subscription_cancelled: 'Subscription cancelled',
    no_description: 'No description',
    last_update: 'Last update',
    activating: 'Activating...',
    view: 'View',
    factures: 'Invoices',
    project_name: 'Project name',
    add_project: 'Add project',
    add_prospect: 'Add prospect',
    subject: 'Subject',
    no_newsletters_found: 'No newsletter found',
    facture_status: 'Invoice status',
    planning: 'Planning',
    dates: 'Dates',
    project_updated_success: 'Project updated successfully',

    // Project Sharing & Collaboration
    share_project: 'Share project',
    share: 'Share',
    invite: 'Invite',
    members: 'Members',
    invite_by_email: 'Invite by email',
    permission: 'Permission',
    view_only: 'View only',
    can_edit: 'Can edit',
    or: 'or',
    copy_share_link: 'Copy share link',
    pending_invitations: 'Pending invitations',
    no_collaborators: 'No collaborators yet',
    collaborators: 'Collaborators',
    manage_collaborators: 'Manage collaborators',
    owner: 'Owner',
    your_role: 'Your role',
    collaborator: 'Collaborator',
    share_note: 'Invited collaborators cannot delete this project.',
    invitation_sent_success: 'Invitation sent successfully',
    invitation_error: 'Error sending invitation',
    link_copied: 'Link copied to clipboard',
    copy_error: 'Error copying',
    invitation_cancelled: 'Invitation cancelled',
    collaborator_removed: 'Collaborator removed',
    error_generic: 'An error occurred',

    // Notifications
    mark_all_read: 'Mark all as read',
    no_notifications: 'No notifications',
    accept: 'Accept',
    reject: 'Reject',
    all_marked_read: 'All notifications marked as read',
    notification_deleted: 'Notification deleted',
    invitation_accepted: 'Invitation accepted! The project has been added to your list.',
    invitation_rejected: 'Invitation rejected',
    view_all_notifications: 'View all notifications',
    just_now: 'Just now',
    
    // Project Invitation
    project_invitation: 'Collaboration invitation',
    invites_you_to_collaborate: 'invites you to collaborate on the project',
    collaborator_note: 'As a collaborator, you will not be able to delete this project.',
    back_to_projects: 'Back to projects',
    expires_on: 'Expires on',
    invitation_not_found: 'Invitation not found or expired',
    invitation_already_accepted: 'This invitation has already been accepted',
    invitation_already_rejected: 'This invitation has been rejected',
    invitation_expired: 'This invitation has expired',

    // Project tasks
    project_tasks: 'Project Tasks',
    tasks_pending: 'tasks pending',
    tasks_completed: 'tasks completed',
    progress: 'progress',
    overall_progress: 'Overall progress',
    add_task: 'New task',
    new_task: 'New task',
    task_title: 'Task title',
    task_description: 'Description (optional)',
    task_created: 'Task created successfully',
    task_updated: 'Task updated',
    task_deleted: 'Task deleted',
    confirm_delete_task: 'Delete this task?',
    edit_task: 'Edit task',
    no_tasks: 'No tasks for this project',
    no_tasks_filter: 'No tasks with this status',
    add_first_task: 'Add a task',
    priority: 'Priority',
    priority_low: 'Low',
    priority_medium: 'Medium',
    priority_high: 'High',
    priority_urgent: 'Urgent',
    task_status_todo: 'To do',
    task_status_in_progress: 'In progress',
    task_status_completed: 'Completed',
    task_status_cancelled: 'Cancelled',
    estimated_hours: 'Estimated hours',
    actual_hours: 'Actual hours',
    no_collaborators_yet: 'No collaborators yet',

    // ProjectTasks - Views
    cards: 'Cards',
    table: 'Table',
    gantt: 'Gantt',

    // ProjectTasks - Statuses
    todo: 'To do',
    cancelled: 'Cancelled',

    // ProjectTasks - Priorities
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',

    // ProjectTasks - Misc
    late: 'Late',
    week_short: 'Week',
    task: 'Task',
    export_pdf: 'Export PDF',
    exporting: 'Exporting...',
    exported_on: 'Exported on',
    export_mode: 'Export mode',
    choose_export_theme: 'Choose the PDF theme:',
    light: 'Light',
    dark: 'Dark',
    export: 'Export',
    file_name: 'File name',
    manage: 'Manage',
    due_dates: 'Due dates',
    billed: 'Billed',

    // Notifications page
    notifications_description: 'Manage your notifications and invitations',
    no_notifications_desc: 'You have no notifications at the moment.',
    today: 'Today',
    yesterday: 'Yesterday',
    this_week: 'This week',
    older: 'Older',
    unread: 'Unread',
    read: 'Read',
    filters: 'Filters',
    notification_type: 'Notification type',
    all_types: 'All types',
    updates: 'Updates',
    system: 'System',
    invitation: 'Invitation',
    update: 'Update',
    selected: 'selected',
    mark_read: 'Mark read',
    selected_marked_read: 'Selected notifications marked as read',
    selected_deleted: 'Notifications deleted',
    mark_as_read: 'Mark as read',
    refresh: 'Refresh',

    // Newsletter Compose
    create_newsletter: 'Create a newsletter',
    select_template: 'Select a template',
    choose_template: 'Choose a template',
    choose_template_desc: 'Select the style that best matches your message',
    template_standard: 'Standard',
    template_standard_desc: 'Classic newsletter for your regular updates',
    template_promotional: 'Promotional',
    template_promotional_desc: 'Ideal for announcing offers and promotions',
    template_announcement: 'Announcement',
    template_announcement_desc: 'For big news and important announcements',
    template_custom: 'Custom',
    template_custom_desc: 'Create your own design from scratch',
    feature_clean_design: 'Clean design',
    feature_content_focus: 'Content focus',
    feature_ideal_updates: 'Ideal for updates',
    feature_promo_badge: 'Promo badge',
    feature_prominent_cta: 'Prominent CTA',
    feature_ideal_offers: 'Ideal for offers',
    feature_visual_impact: 'Strong visual impact',
    feature_centered_message: 'Centered message',
    feature_ideal_events: 'Ideal for events',
    feature_total_freedom: 'Total freedom',
    feature_no_constraints: 'No constraints',
    feature_unique_design: 'Unique design',
    preview: 'Preview',
    send: 'Send',
    previous: 'Previous',
    next: 'Next',
    step_template: 'Template',
    step_content: 'Content',
    step_recipients: 'Recipients',
    step_send: 'Send',
    write_content: 'Write your content',
    write_content_desc: 'Customize your newsletter content',
    footer: 'Footer',
    customize_footer: 'Customize footer',
    first_name_label: 'First name',
    last_name_label: 'Last name',
    email_label: 'Email',
    phone_label: 'Phone',
    website_label: 'Website',
    linkedin_label: 'LinkedIn',
    twitter_label: 'Twitter / X',
    instagram_label: 'Instagram',
    facebook_label: 'Facebook',
    custom_text_label: 'Custom text (optional)',
    custom_text_placeholder: 'Additional message in footer...',
    unsubscribe_text_label: 'Unsubscribe text',
    email_title_label: 'Email title',
    email_title_placeholder: 'Ex: Welcome to our newsletter',
    email_subject_label: 'Email subject',
    email_subject_hint: 'visible in inbox',
    email_subject_placeholder: 'Ex: Discover our new features',
    message_label: 'Message',
    add_image: 'Add image',
    cta_section_title: 'Action button (optional)',
    cta_text_label: 'Button text',
    cta_text_placeholder: 'Ex: Learn more',
    cta_link_label: 'Link',
    banner_section_title: 'End banner (optional)',
    add_banner: 'Add banner',
    banner_hint: 'PNG, JPG up to 5 MB',
    select_recipients: 'Select recipients',
    select_recipients_desc: 'Choose who will receive your newsletter',
    select_all_clients: 'Select all clients',
    recipients_selected: 'selected',
    review_and_send: 'Review and send',
    review_and_send_desc: 'Final check before sending',
    ready_to_send: 'Ready to send?',
    newsletter_will_be_sent: 'Your newsletter will be sent to',
    recipients_count: 'recipient(s)',
    send_now: 'Send now',
    sending: 'Sending...',
    contacts: 'contact(s)',
    others: 'others',
    mailbox_preview: 'Mailbox Preview',
    inbox: 'Inbox',
    favorites: 'Favorites',
    sent_folder: 'Sent',
    archives: 'Archives',
    trash: 'Trash',
    search_placeholder: 'Search...',
    now: 'Now',
    to_me: 'to me',
    select_template_preview: 'Select a template to see preview',
    write_message_placeholder: 'Write your message here...',
    your_title_here: 'Your title here',
    content_preview_placeholder: 'Your content will appear here...',
    special_offer: 'SPECIAL OFFER',
    unsubscribe: 'Unsubscribe',
    please_select_recipient: 'Please select at least one recipient',
    please_enter_subject: 'Please enter a subject',
    newsletter_sent_success: 'Newsletter sent to',
    newsletter_send_error: 'Error sending newsletter',
    newsletter_not_found: 'Newsletter not found',
    newsletter_detail: 'Newsletter Detail',
    loading_newsletter: 'Loading newsletter...',
    back_to_newsletters: 'Back to newsletters',
    sent_at: 'Sent at',
    email_content: 'Email Content',
    no_content: 'No content',
    subscribers: 'Recipients',
    no_subscribers: 'No recipients',
    quick_stats: 'Quick Stats',
    total_recipients: 'Total recipients',
    email_preview: 'Email Preview',
    email_preview_description: 'See the email in your inbox',
    please_select_image: 'Please select an image',
    image_max_size: 'Image must not exceed 5 MB',
    toolbar_heading1: 'Heading 1',
    toolbar_heading2: 'Heading 2',
    toolbar_paragraph: 'Paragraph',
    toolbar_bold: 'Bold',
    toolbar_italic: 'Italic',
    toolbar_bullet_list: 'Bullet list',
    toolbar_numbered_list: 'Numbered list',
    toolbar_align_left: 'Align left',
    toolbar_align_center: 'Center',
    toolbar_align_right: 'Align right',
    toolbar_text_color: 'Text color',
    toolbar_insert_link: 'Insert link',
    author: 'Author',

    automatic_status: 'Automatic status',
    blue: 'Blue',
    emerald: 'Emerald',
    amber: 'Amber',
    purple: 'Purple',
    rose: 'Rose',
    cyan: 'Cyan',

    overview: 'Overview',
    tasks: 'Tasks',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr');

  useEffect(() => {
    // Récupérer la langue depuis localStorage au chargement
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'fr' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
